/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import connexion.Connexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.mail.*;
import javax.mail.internet.*;
import java.util.Properties;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Yoga
 */
public class Email extends javax.swing.JFrame {

    int randomCode;

    /**
     * Creates new form Email
     */
    public Email() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtCode = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        bnEnvoyer = new javax.swing.JButton();
        bnVérifier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bnBackLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCode.setText("Password");
        txtCode.setBorder(null);
        txtCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodeFocusGained(evt);
            }
        });
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        jPanel3.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 370, 30));

        txtEmail.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        txtEmail.setText("Entrer Email");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 300, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 390, 10));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 10));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 3, 30)); // NOI18N
        jLabel6.setText("ENVOI PAR EMAIL ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 290, 100));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 390, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gmail.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 140, 110));

        bnEnvoyer.setBackground(new java.awt.Color(255, 255, 255));
        bnEnvoyer.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        bnEnvoyer.setText("Envoyer");
        bnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnEnvoyerActionPerformed(evt);
            }
        });
        jPanel3.add(bnEnvoyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        bnVérifier.setBackground(new java.awt.Color(255, 255, 255));
        bnVérifier.setText("Vérifier Code");
        bnVérifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnVérifierActionPerformed(evt);
            }
        });
        jPanel3.add(bnVérifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lettreEmail.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 30, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passwordEmail.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 40, 40));

        bnBackLog.setBackground(new java.awt.Color(255, 255, 255));
        bnBackLog.setText("Page login");
        bnBackLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnBackLogActionPerformed(evt);
            }
        });
        jPanel3.add(bnBackLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        jPanel3.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodeFocusGained
        // TODO add your handling code here:
        txtCode.setText("");
    }//GEN-LAST:event_txtCodeFocusGained

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void bnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnEnvoyerActionPerformed
        // TODO add your handling code here:
        String to = txtEmail.getText().trim();

        Random rand = new Random();
        int randomCode = 100000 + rand.nextInt(900000);

        String user = "ouarsalma34@gmail.com";
            String pass = "fptc ietn mqha iejq";


        String subject = "Code de réinitialisation";
        String message = "Votre code est : " + randomCode;

        Properties pros = new Properties();
        pros.put("mail.smtp.auth", "true");
        pros.put("mail.smtp.starttls.enable", "true");
        pros.put("mail.smtp.host", "smtp.gmail.com");
        pros.put("mail.smtp.port", "587");
        pros.put("mail.smtp.starttls.required", "true");

        Session session = Session.getInstance(pros, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(user, pass);
            }
        });

        try {
            Message msg = new MimeMessage(session);
            msg.setFrom(new InternetAddress(user));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            msg.setSubject(subject);
            msg.setText(message);

            Transport.send(msg); // ← ici plus d'erreur
            JOptionPane.showMessageDialog(this, "Code envoyé avec succès à " + to);

            // Enregistrer le code dans la BDD
            Connection dbcn = Connexion.getInstance().getCn();
            PreparedStatement updateSt = dbcn.prepareStatement("UPDATE users SET verification_code = ? WHERE email = ?");
            updateSt.setString(1, String.valueOf(randomCode));
            updateSt.setString(2, to);
            updateSt.executeUpdate();
            updateSt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'envoi : " + e.getMessage());
        }


    }//GEN-LAST:event_bnEnvoyerActionPerformed

    private void bnVérifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnVérifierActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText().trim();
        String codeSaisi = txtCode.getText().trim();

        if (email.isEmpty() || codeSaisi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir l'email et le code.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection dbcn = Connexion.getInstance().getCn();

        try {
            String query = "SELECT verification_code FROM users WHERE email = ?";
            PreparedStatement st = dbcn.prepareStatement(query);
            st.setString(1, email);
            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                String codeStocké = rs.getString("verification_code");

                if (codeSaisi.equals(codeStocké)) {
                    JOptionPane.showMessageDialog(this, "Code correct. Vous pouvez réinitialiser votre mot de passe.", "Succès", JOptionPane.INFORMATION_MESSAGE);

                    this.dispose();

                    Reset reset = new Reset(email);
                    reset.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Code incorrect.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Email introuvable.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }

            rs.close();
            st.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bnVérifierActionPerformed

    private void bnBackLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnBackLogActionPerformed
        // TODO add your handling code here:
        dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_bnBackLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Email().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnBackLog;
    private javax.swing.JButton bnEnvoyer;
    private javax.swing.JButton bnVérifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPasswordField txtCode;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
