/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.mysql.jdbc.Connection;
import connexion.Connexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.PasswordUtils;

/**
 *
 * @author Yoga
 */
public class MpOublié extends javax.swing.JFrame {

    /**
     * Creates new form MpOublié
     */
    public MpOublié() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        bnMpoLogin = new javax.swing.JTextField();
        txtPasswordMpO = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Enregistrer = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backLogIn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtRepSecret = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCfPassword = new javax.swing.JPasswordField();
        bnChercherLogin = new javax.swing.JButton();
        txtQuestionS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ViaEmail = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4), "Mot de passe oublié ?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei", 3, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bnMpoLogin.setBackground(new java.awt.Color(102, 0, 51));
        bnMpoLogin.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        bnMpoLogin.setForeground(new java.awt.Color(255, 255, 255));
        bnMpoLogin.setText("Login");
        bnMpoLogin.setBorder(null);
        bnMpoLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bnMpoLoginFocusGained(evt);
            }
        });
        bnMpoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnMpoLoginActionPerformed(evt);
            }
        });
        jPanel3.add(bnMpoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 170, 30));

        txtPasswordMpO.setBackground(new java.awt.Color(102, 0, 51));
        txtPasswordMpO.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordMpO.setText("NvPassword");
        txtPasswordMpO.setBorder(null);
        txtPasswordMpO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordMpOFocusGained(evt);
            }
        });
        txtPasswordMpO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordMpOActionPerformed(evt);
            }
        });
        jPanel3.add(txtPasswordMpO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 300, 30));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, 330, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/utilisateur.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 40, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verrouiller-alt.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 30, 50));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 330, 10));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 330, 10));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 330, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/penne (1).png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question (1).png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 40, 40));

        Enregistrer.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        Enregistrer.setForeground(new java.awt.Color(255, 255, 255));
        Enregistrer.setText("     Enregistrer");
        Enregistrer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Enregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnregistrerMouseClicked(evt);
            }
        });
        jPanel3.add(Enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 720, 140, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fleche-vers-le-bas.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 720, 40, 50));

        backLogIn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        backLogIn.setForeground(new java.awt.Color(255, 255, 255));
        backLogIn.setText("    Connexion");
        backLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLogInMouseClicked(evt);
            }
        });
        jPanel3.add(backLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 140, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fleche-vers-le-bas (1).png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 720, 50, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 140));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 3, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Veuillez remplir ces champs :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 300, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mot-de-passe (1).png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 140, 80));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 330, 10));

        txtRepSecret.setBackground(new java.awt.Color(102, 0, 51));
        txtRepSecret.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        txtRepSecret.setForeground(new java.awt.Color(255, 255, 255));
        txtRepSecret.setText("Réponse de sécurité");
        txtRepSecret.setBorder(null);
        txtRepSecret.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRepSecretFocusGained(evt);
            }
        });
        txtRepSecret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepSecretActionPerformed(evt);
            }
        });
        jPanel3.add(txtRepSecret, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 330, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nouveau mot de passe :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 170, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verrouiller-alt.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 30, 50));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Confirmer mot de passe :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 180, 30));

        txtCfPassword.setBackground(new java.awt.Color(102, 0, 51));
        txtCfPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtCfPassword.setText("CfPassword");
        txtCfPassword.setBorder(null);
        txtCfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCfPasswordFocusGained(evt);
            }
        });
        jPanel3.add(txtCfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 636, 270, 30));

        bnChercherLogin.setBackground(new java.awt.Color(102, 0, 51));
        bnChercherLogin.setForeground(new java.awt.Color(255, 255, 255));
        bnChercherLogin.setText("Chercher");
        bnChercherLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnChercherLoginActionPerformed(evt);
            }
        });
        jPanel3.add(bnChercherLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        txtQuestionS.setBackground(new java.awt.Color(102, 0, 51));
        txtQuestionS.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        txtQuestionS.setForeground(new java.awt.Color(255, 255, 255));
        txtQuestionS.setText("Question de sécurité");
        txtQuestionS.setBorder(null);
        txtQuestionS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuestionSFocusGained(evt);
            }
        });
        jPanel3.add(txtQuestionS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 330, 40));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("- Vous avez encore des difficultés à vous rappeler la réponse ?");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 440, 50));

        ViaEmail.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        ViaEmail.setForeground(new java.awt.Color(255, 255, 255));
        ViaEmail.setText("   Essayer via Email");
        ViaEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViaEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViaEmailMouseClicked(evt);
            }
        });
        jPanel3.add(ViaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 860, 150, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fleches-vers-le-bas.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 80, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fleches-vers-le-bas.png"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnMpoLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bnMpoLoginFocusGained
        // TODO add your handling code here:
        bnMpoLogin.setText("");
    }//GEN-LAST:event_bnMpoLoginFocusGained

    private void bnMpoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnMpoLoginActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bnMpoLoginActionPerformed

    private void txtPasswordMpOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordMpOFocusGained
        // TODO add your handling code here:
        txtPasswordMpO.setText("");
    }//GEN-LAST:event_txtPasswordMpOFocusGained

    private void txtPasswordMpOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordMpOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordMpOActionPerformed

    private void EnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnregistrerMouseClicked
        // TODO add your handling code here:

        String login = bnMpoLogin.getText().trim();
        String question_secrete = txtQuestionS.getText().trim();
        String reponseSecrete = txtRepSecret.getText().trim();
        String newPassword = String.valueOf(txtPasswordMpO.getPassword()).trim();
        String confirmPassword = String.valueOf(txtCfPassword.getPassword()).trim();

        //if (email.isEmpty() || login.isEmpty() || nvpassword.isEmpty()||reponse_secrete.isEmpty() ) {
        //    JOptionPane.showMessageDialog(this, "Remplir tous les champs !", "Error", JOptionPane.ERROR_MESSAGE);
        //}else{}
        if (login.isEmpty() || reponseSecrete.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Les mots de passe ne correspondent pas.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection dbcn = (Connection) Connexion.getInstance().getCn();

        if (dbcn != null) {
            try {

                String query = "SELECT reponse_secrete FROM users WHERE login = ?";
                PreparedStatement st = dbcn.prepareStatement(query);
                st.setString(1, login);
                ResultSet rs = st.executeQuery();

                if (rs.next()) {
                    String storedReponse = rs.getString("reponse_secrete");

                    if (!storedReponse.equalsIgnoreCase(reponseSecrete)) {
                        JOptionPane.showMessageDialog(this, "Réponse secrète incorrecte.", "Erreur", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Utilisateur introuvable.", "Erreur", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                String newSalt = PasswordUtils.generateSalt();
                String hashedPassword = PasswordUtils.hashPassword(newPassword, newSalt);

                String updateQuery = "UPDATE users SET password = ?, salt = ? WHERE login = ?";
                PreparedStatement updateSt = dbcn.prepareStatement(updateQuery);
                updateSt.setString(1, hashedPassword);
                updateSt.setString(2, newSalt);
                updateSt.setString(3, login);
                int rowsUpdated = updateSt.executeUpdate();

                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Mot de passe mis à jour avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new Login().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Échec de la mise à jour du mot de passe.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }

                rs.close();
                st.close();
                updateSt.close();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Connexion à la base de données échouée.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_EnregistrerMouseClicked

    private void backLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLogInMouseClicked
        // TODO add your handling code here:
        dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_backLogInMouseClicked

    private void txtRepSecretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepSecretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepSecretActionPerformed

    private void txtRepSecretFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRepSecretFocusGained
        // TODO add your handling code here:
        txtRepSecret.setText("");
    }//GEN-LAST:event_txtRepSecretFocusGained

    private void txtCfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCfPasswordFocusGained
        // TODO add your handling code here:
        txtCfPassword.setText("");
    }//GEN-LAST:event_txtCfPasswordFocusGained

    private void bnChercherLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnChercherLoginActionPerformed
        // TODO add your handling code here:
        String login = bnMpoLogin.getText().trim();

        if (login.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer un login.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection dbcn = (Connection) Connexion.getInstance().getCn();

        if (dbcn != null) {
            try {

                String query = "SELECT question_secrete FROM users WHERE login = ?";
                PreparedStatement st = dbcn.prepareStatement(query);
                st.setString(1, login);

                ResultSet rs = st.executeQuery();

                if (rs.next()) {
                    txtQuestionS.setText(rs.getString("question_secrete"));
                } else {
                    JOptionPane.showMessageDialog(this, "Login incorrect ou inexistant.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }

                rs.close();
                st.close();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(MpOublié.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Connexion à la base de données échouée.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bnChercherLoginActionPerformed

    private void txtQuestionSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuestionSFocusGained
        // TODO add your handling code here:
        txtQuestionS.setText("");
    }//GEN-LAST:event_txtQuestionSFocusGained

    private void ViaEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViaEmailMouseClicked
        // TODO add your handling code here:
        dispose();
        Email e = new Email();
        e.setVisible(true);
    }//GEN-LAST:event_ViaEmailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MpOublié.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MpOublié.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MpOublié.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MpOublié.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MpOublié().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Enregistrer;
    private javax.swing.JLabel ViaEmail;
    private javax.swing.JLabel backLogIn;
    private javax.swing.JButton bnChercherLogin;
    private javax.swing.JTextField bnMpoLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPasswordField txtCfPassword;
    private javax.swing.JPasswordField txtPasswordMpO;
    private javax.swing.JTextField txtQuestionS;
    private javax.swing.JTextField txtRepSecret;
    // End of variables declaration//GEN-END:variables
}
