/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import connexion.Connexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import utils.PasswordUtils;

/**
 *
 * @author Yoga
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        bnRegLogin = new javax.swing.JTextField();
        txtPasswordReg = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bnSignUpReg = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backLogIn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboQst = new javax.swing.JComboBox();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtReponseSecurite = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bnRegLogin.setBackground(new java.awt.Color(102, 0, 51));
        bnRegLogin.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        bnRegLogin.setForeground(new java.awt.Color(255, 255, 255));
        bnRegLogin.setText("Login");
        bnRegLogin.setBorder(null);
        bnRegLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bnRegLoginFocusGained(evt);
            }
        });
        bnRegLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnRegLoginActionPerformed(evt);
            }
        });
        jPanel3.add(bnRegLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 370, 30));

        txtPasswordReg.setBackground(new java.awt.Color(102, 0, 51));
        txtPasswordReg.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordReg.setText("Password");
        txtPasswordReg.setBorder(null);
        txtPasswordReg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordRegFocusGained(evt);
            }
        });
        txtPasswordReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordRegActionPerformed(evt);
            }
        });
        jPanel3.add(txtPasswordReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 370, 30));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 390, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/utilisateur.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 40, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verrouiller-alt.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 30, 50));

        txtNom.setBackground(new java.awt.Color(102, 0, 51));
        txtNom.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        txtNom.setForeground(new java.awt.Color(255, 255, 255));
        txtNom.setText("Nom");
        txtNom.setBorder(null);
        txtNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomFocusGained(evt);
            }
        });
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        jPanel3.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 300, 40));

        txtPrenom.setBackground(new java.awt.Color(102, 0, 51));
        txtPrenom.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        txtPrenom.setForeground(new java.awt.Color(255, 255, 255));
        txtPrenom.setText("Prénom");
        txtPrenom.setBorder(null);
        txtPrenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrenomFocusGained(evt);
            }
        });
        jPanel3.add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 300, 40));

        txtEmail.setBackground(new java.awt.Color(102, 0, 51));
        txtEmail.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 300, 40));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 390, 10));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 390, 10));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 390, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nom.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nom.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 40, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 40, 30));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 390, 10));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 500, 10));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CRÉER UN COMPTE !");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 374, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formulaire-dinscription.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 120));

        bnSignUpReg.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        bnSignUpReg.setForeground(new java.awt.Color(255, 255, 255));
        bnSignUpReg.setText("       Sign up");
        bnSignUpReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bnSignUpReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnSignUpRegMouseClicked(evt);
            }
        });
        jPanel3.add(bnSignUpReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 140, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fleche-vers-le-bas.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 40, 50));

        backLogIn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        backLogIn.setForeground(new java.awt.Color(255, 255, 255));
        backLogIn.setText("         Log in");
        backLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLogInMouseClicked(evt);
            }
        });
        jPanel3.add(backLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 140, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fleche-vers-le-bas (1).png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 40, 40));

        ComboQst.setBackground(new java.awt.Color(102, 0, 51));
        ComboQst.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Questions de sécurité. Veuillez choisir !", "Quel est le nom de votre premier animal de compagnie ?", "Quelle est la ville de naissance de votre mère ?", "Quel est le nom de votre enseignant(e) préféré(e) au primaire ?" }));
        jPanel3.add(ComboQst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 390, 40));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 390, 10));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 390, 10));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/penne (1).png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 40, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question (1).png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 40, 50));

        txtReponseSecurite.setBackground(new java.awt.Color(102, 0, 51));
        txtReponseSecurite.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        txtReponseSecurite.setForeground(new java.awt.Color(255, 255, 255));
        txtReponseSecurite.setText("Réponse sécurité");
        txtReponseSecurite.setBorder(null);
        txtReponseSecurite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtReponseSecuriteFocusGained(evt);
            }
        });
        txtReponseSecurite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReponseSecuriteActionPerformed(evt);
            }
        });
        jPanel3.add(txtReponseSecurite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 370, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnRegLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bnRegLoginFocusGained
        // TODO add your handling code here:
        bnRegLogin.setText("");
    }//GEN-LAST:event_bnRegLoginFocusGained

    private void bnRegLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnRegLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnRegLoginActionPerformed

    private void txtPasswordRegFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordRegFocusGained
        // TODO add your handling code here:
        txtPasswordReg.setText("");
    }//GEN-LAST:event_txtPasswordRegFocusGained

    private void txtPasswordRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordRegActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void bnSignUpRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnSignUpRegMouseClicked
        // TODO add your handling code here:
        String nom = txtNom.getText();
        String prenom = txtPrenom.getText();
        String email = txtEmail.getText();
        String login = bnRegLogin.getText();
        String password = String.valueOf(txtPasswordReg.getPassword());
        String question_secrete = (String) ComboQst.getSelectedItem();
        String reponse_secrete = txtReponseSecurite.getText();
        if (email.isEmpty() || login.isEmpty() || password.isEmpty()
                || nom.isEmpty() || prenom.isEmpty() || question_secrete.isEmpty() || reponse_secrete.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Remplir tous les champs !", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            userRegister(nom, prenom, email, login, password, question_secrete, reponse_secrete);
        }

    }//GEN-LAST:event_bnSignUpRegMouseClicked


    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailFocusGained

    private void backLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLogInMouseClicked
        // TODO add your handling code here:
        dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_backLogInMouseClicked

    private void txtPrenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrenomFocusGained
        // TODO add your handling code here:
        txtPrenom.setText("");
    }//GEN-LAST:event_txtPrenomFocusGained

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtNomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomFocusGained
        // TODO add your handling code here:
        txtNom.setText("");
    }//GEN-LAST:event_txtNomFocusGained

    private void txtReponseSecuriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReponseSecuriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReponseSecuriteActionPerformed

    private void txtReponseSecuriteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReponseSecuriteFocusGained
        // TODO add your handling code here:
        txtReponseSecurite.setText("");
    }//GEN-LAST:event_txtReponseSecuriteFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboQst;
    private javax.swing.JLabel backLogIn;
    private javax.swing.JTextField bnRegLogin;
    private javax.swing.JLabel bnSignUpReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNom;
    private javax.swing.JPasswordField txtPasswordReg;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtReponseSecurite;
    // End of variables declaration//GEN-END:variables

    private void userRegister(String nom, String prenom, String email, String login, String password,
            String question_secrete, String reponse_secrete) {
        Connection dbcn = (Connection) Connexion.getInstance().getCn();

        if (dbcn != null) {
            try {
                // Génération du sel
                String salt = PasswordUtils.generateSalt();

                // Hachage du mot de passe avec le sel
                String hashedPassword = PasswordUtils.hashPassword(password, salt);

                // Requête SQL mise à jour avec le champ 'salt'
                String query = "INSERT INTO users (nom, prenom, email, login, password, salt, question_secrete, reponse_secrete) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement st = (PreparedStatement) dbcn.prepareStatement(query);
                st.setString(1, nom);
                st.setString(2, prenom);
                st.setString(3, email);
                st.setString(4, login);
                st.setString(5, hashedPassword);
                st.setString(6, salt);
                st.setString(7, question_secrete);
                st.setString(8, reponse_secrete);

                int rs = st.executeUpdate();

                if (rs > 0) {
                    JOptionPane.showMessageDialog(this, "Utilisateur inscrit avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new Login().setVisible(true);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erreur lors de l'inscription : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "La connexion à la base de données a échoué.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
}
