/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import services.AdhesionService;
import beans.Club;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.plot.PlotOrientation;
import services.ClubService;

/**
 *
 * @author Yoga
 */
public class StatMembresParClub extends javax.swing.JInternalFrame {

    /**
     * Creates new form StatMembresParClub
     */
    public StatMembresParClub() {
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);

        initComponents();
        afficherGraphique();

        this.setSize(800, 500);
        this.setLocation(
                (getParent() != null ? getParent().getWidth() / 2 - getWidth() / 2 : 200),
                (getParent() != null ? getParent().getHeight() / 2 - getHeight() / 2 : 100)
        );
    }

    private void afficherGraphique() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        AdhesionService as = new AdhesionService();
        ClubService cs = new ClubService();

        for (Club c : cs.findAll()) {
            int nbMembres = as.findByClub(c).size();
            dataset.setValue(nbMembres, "Nombre de membres", c.getNom());
        }

        JFreeChart barChart = ChartFactory.createBarChart(
                "Nombre de membres par club",
                "Clubs",
                "Nombre de membres",
                dataset,
                PlotOrientation.VERTICAL,
                false, true, false);

        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        setContentPane(chartPanel);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
